# This is a basic workflow to help you get started with Actions
name: Continuous Deployment

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  workflow_dispatch:
#  push:
#      branches:
#      - main

# Permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  DockerBuildPush:
    uses: ./.github/workflows/build_push_docker.yaml
    with:
      docker_filepath: Dockerfile
      repository_name: innervaul
    secrets: inherit
#  Terraform:
#    name: TerraformApply
##    needs: [ DockerBuildPush ]
#    uses: ./.github/workflows/terraform.yaml
#    with:
#      region: eu-west-1
#      terraform-action: apply
#      terraform-directory: infra/terraform
#    secrets: inherit
